name: NuGet Generation

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
env:
  project_path: /home/runner/work/Wolf.Utilities/Wolf.Utilities

jobs:
  build:
    runs-on: self-hosted

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
      USERNAME: daniel-filipe-lobo
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #- name: Setup .NET Core @ Latest
      #  uses: actions/setup-dotnet@v4
      #  with:
      #    dotnet-version: '9.x'
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --no-restore --configuration Release

      - name: NuGet pack
        run: dotnet pack --no-build --configuration Release --output ./nupkgs
          
      - name: NuGet add source
        run: |
          $hasSource = dotnet nuget list source | Select-String -Pattern 'github2' -CaseSensitive -SimpleMatch
          if ($hasSource.Count -gt 0)
          {
            dotnet nuget add source --username ${{ env.USERNAME }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ env.USERNAME }}/index.json"
          }

      - name: NuGet push
        run: dotnet nuget push .\nupkgs\*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}
      