name: NuGet Generation

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
env:
  project_path: /home/runner/work/Wolf.Utilities/Wolf.Utilities

jobs:
  build:
    runs-on: ubuntu-lateste

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --no-restore --configuration Release

      - name: Publish application
        run: dotnet publish --no-build --configuration Release -o ./publish

      - name: Publish package to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
          OWNER: daniel-filipe-lobo
        run: |
          dotnet nuget add source --username $OWNER --password $GITHUB_TOKEN --store-password-in-clear-text --name github "https://nuget.pkg.github.com/$OWNER/index.json"
          dotnet pack --configuration Release --output ./nupkgs
          dotnet nuget push ./nupkgs/*.nupkg --source github
      #- name: Build solution and generate NuGet package
      #  run: |  
      #    cd $project_path
      #    dotnet pack -c Release -o out

      #- name: Push generated package to GitHub registry
      #  run: dotnet nuget push ./<project>/out/*.nupkg --skip-duplicate --no-symbols true
