name: NuGet Generation

on:
  push:
    branches: 
      - main
  pull_request:
    types: [closed]
    branches:
      - main
env:
  project_path: /home/runner/work/Wolf.Utilities/Wolf.Utilities

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        
          
      - name: Build solution and generate NuGet package
        run: |  
          cd $project_path
          dotnet pack -c Release -o out

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./<project>/out/*.nupkg --skip-duplicate --no-symbols true
