name: NuGet Generation

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
env:
  project_path: /home/runner/work/Wolf.Utilities/Wolf.Utilities
  project: Wolf.Utilities

jobs:
  build:
    runs-on: self-hosted

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
      USERNAME: daniel-filipe-lobo
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build ${{ env.project }}.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.project }}.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: NuGet pack
        run: dotnet pack --configuration Release --no-build --output ./nupkgs
          
      - name: NuGet add source
        run: |
          $hasSource = dotnet nuget list source | Select-String -Pattern 'github' -CaseSensitive -SimpleMatch
          if ($hasSource.Count -eq 0)
          {
            dotnet nuget add source --username ${{ env.USERNAME }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ env.USERNAME }}/index.json"
          }

      - name: NuGet push
        run: dotnet nuget push .\nupkgs\*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}
      